language: go

go:
  - 1.x
  - 1.11.x

env:
  - GO111MODULE=on

install: true

script:
  - set -e
  - fmt=$(gofmt -l -s .)
  - test -z $fmt || (echo "please run gofmt" ; echo $fmt ; exit 1)
  - go run golang.org/x/lint/golint -set_exit_status $(go list ./...)
  - go test -race -vet=all ./...
