// Code generated by flamingo.me/graphql, DO NOT EDIT.
//+build !graphql

package graphql

import (
	"flamingo.me/dingo"
	"github.com/99designs/gqlgen/graphql"
)

type Module struct{}

func (*Module) Configure(injector *dingo.Injector) {
	injector.Bind(new(graphql.ExecutableSchema)).ToProvider(func(root *rootResolver) graphql.ExecutableSchema {
		return NewExecutableSchema(Config{Resolvers: root})
	})
}
