//Code generated by flamingo.me/graphql DO NOT EDIT!
//+build graphql

package graphql

import "flamingo.me/dingo"

// this empty module is used by go generate to provide a dingo module because module.go is not compiled during generate
type Module struct{}

func (Module) Configure(injector *dingo.Injector) {

}
